nome=input("Diga o nome do arquivo a ser aberto:")
try:
    file = open(nome, 'r')
except:
    print("O arquivo não existe")
else:

    texto=file.read().lower().replace('\n', '')

    a = texto.count('a')
    b = texto.count('b')
    c = texto.count('c')
    d = texto.count('d')
    e = texto.count('e')
    f = texto.count('f')
    g = texto.count('g')
    h = texto.count('h')
    i = texto.count('i')
    j = texto.count('j')
    k = texto.count('k')
    l = texto.count('l')
    m = texto.count('m')
    n = texto.count('n')
    o = texto.count('o')
    p = texto.count('p')
    q = texto.count('q')
    r = texto.count('r')
    s = texto.count('s')
    t = texto.count('t')
    u = texto.count('u')
    v = texto.count('v')
    w = texto.count('w')
    x = texto.count('x')
    y = texto.count('y')
    z = texto.count('z')

    print(f"letra 'a' = {a}")
    print(f"letra 'b' = {b}")
    print(f"letra 'c' = {c}")
    print(f"letra 'd' = {d}")
    print(f"letra 'e' = {e}")
    print(f"letra 'f' = {f}")
    print(f"letra 'g' = {g}")
    print(f"letra 'h' = {h}")
    print(f"letra 'i' = {i}")
    print(f"letra 'j' = {j}")
    print(f"letra 'k' = {k}")
    print(f"letra 'l' = {l}")
    print(f"letra 'm' = {m}")
    print(f"letra 'n' = {n}")
    print(f"letra 'o' = {o}")
    print(f"letra 'p' = {p}")
    print(f"letra 'q' = {q}")
    print(f"letra 'r' = {r}")
    print(f"letra 's' = {s}")
    print(f"letra 't' = {t}")
    print(f"letra 'u' = {u}")
    print(f"letra 'v' = {v}")
    print(f"letra 'w' = {w}")
    print(f"letra 'x' = {x}")
    print(f"letra 'y' = {y}")
    print(f"letra 'z' = {z}")
